自定义层

构造一个没有任何参数的自定义层

In [1]:
import torch
import torch.nn.functional as F
from torch import nn

In [2]:
class CenteredLayer(nn.Module):
    def __init__(self):
        super().__init__()
    def forward(self, X):
        return X - X.mean()

In [3]:
layer = CenteredLayer()

In [4]:
layer(torch.FloatTensor([1, 2, 3, 4, 5]))

tensor([-2., -1.,  0.,  1.,  2.])

将层作为组件合并到构建更复杂的模型中

In [5]:
net = nn.Sequential(nn.Linear(8, 128), CenteredLayer())

In [6]:
Y = net(torch.rand(4,8))

In [7]:
Y.mean()

tensor(8.3819e-09, grad_fn=<MeanBackward0>)

带参数的层

In [8]:
class MyLinear(nn.Module):
    def __init__(self, in_units, units):
        super().__init__()
        self.weight = nn.Parameter(torch.randn(in_units, units))
        self.bias = nn.Parameter(torch.randn(units, ))
    
    def forward(self, X):
        linear = torch.matmul(X, self.weight.data) + self.bias.data
        return F.relu(linear)

In [9]:
dense = MyLinear(5,3)
dense.weight

Parameter containing:
tensor([[-1.2136, -0.9363,  0.7590],
        [-0.2273,  1.4747, -0.3464],
        [ 1.2718, -0.3554,  0.3743],
        [ 0.6483, -1.7690, -0.8894],
        [-0.2434, -0.5702,  1.3251]], requires_grad=True)

使用自定义层直接执行正向传播计算

In [11]:
dense(torch.rand(2, 5))

tensor([[0.7902, 0.0000, 1.2817],
        [1.3971, 0.0000, 2.1779]])

使用自定义层构建模型

In [12]:
net = nn.Sequential(MyLinear(64, 8), MyLinear(8, 1))

In [ ]:
net[torch]