读写文件

加载和保存张量

In [1]:
import torch
from torch import nn
from torch.nn import functional as F

In [2]:
x = torch.arange(4)
x

tensor([0, 1, 2, 3])

In [3]:
torch.save(x,'x-file')

In [4]:
x2 = torch.load('x-file')
x2

tensor([0, 1, 2, 3])

存储一个张量列表，然后把它们读回内存

In [5]:
y = torch.zeros(4)
torch.save([x,y], 'x-files')
x2, y2 = torch.load('x-files')
(x2, y2)

(tensor([0, 1, 2, 3]), tensor([0., 0., 0., 0.]))

写入或读取从字符串映射到张量的字典

In [6]:
mydict = {'x':x, 'y':y}
mydict

{'x': tensor([0, 1, 2, 3]), 'y': tensor([0., 0., 0., 0.])}

In [7]:
torch.save(mydict, 'mydict')
mydict2 = torch.load('mydict')
mydict2

{'x': tensor([0, 1, 2, 3]), 'y': tensor([0., 0., 0., 0.])}

加载和保存模型参数参数

In [8]:
class MLP(nn.Module):
    def __init__(self):
        super().__init__()
        self.hidden = nn.Linear(20, 256)
        self.output = nn.Linear(256, 10)
    def forward(self, x):
        return self.output(F.relu(self.hidden(x)))


In [9]:
net = MLP()

In [10]:
X = torch.randn(size=(6, 20))
X

tensor([[-0.1613, -1.5991,  1.3678,  0.6908, -1.5151,  0.7809,  0.5339,  2.5892,
          1.0175,  1.2038, -0.3501, -0.5157,  0.5920, -1.3720,  0.0464, -1.7235,
         -0.9409, -1.0620, -0.3223,  0.6638],
        [ 0.2858, -1.1495,  0.0955,  0.3977,  0.3220,  1.3780,  1.0631,  0.7806,
          1.0663, -0.6138, -1.7502, -0.4005,  0.5037,  0.3188,  0.7117,  1.4289,
          1.1295, -0.1618,  0.4241, -0.3305],
        [-1.8726, -0.7208,  1.5742,  0.6420, -0.3349, -0.1323, -0.0346,  0.8288,
          0.3881,  0.0625, -1.3627,  0.4627,  0.7728,  0.2374,  0.3082, -1.7586,
         -0.3496,  0.5560,  0.5174,  0.8431],
        [-0.8667, -1.0877,  0.6614,  0.1328, -0.1363, -0.2355,  0.1319,  0.0652,
         -0.5866,  1.3504, -0.8252,  0.6932, -1.0438, -0.7015,  0.4154,  0.1201,
         -0.8650, -1.0247, -0.8024, -1.5008],
        [-0.9525, -1.6476, -0.5218,  0.7450, -1.3324, -1.7252, -0.4003,  2.6915,
          0.5420, -0.0802,  0.2861, -0.9112,  0.7718, -1.0371, -0.6525,  0.0633,
      

In [11]:
Y = net(X)
Y

tensor([[-0.0209,  0.3166, -0.0967,  0.1269, -0.5412,  0.1302, -0.0083,  0.4940,
         -0.0661, -0.4259],
        [ 0.4337,  0.1968, -0.1514,  0.3067, -0.3140,  0.0319, -0.1792,  0.1203,
          0.0494, -0.2147],
        [ 0.0301,  0.4452, -0.2283, -0.0163, -0.6999,  0.3072,  0.0945,  0.1110,
          0.1717, -0.2304],
        [ 0.2101,  0.2193, -0.1392,  0.0105, -0.2784,  0.0883, -0.2607,  0.0741,
          0.1087, -0.2262],
        [ 0.1657,  0.4939,  0.0839,  0.1590, -0.2329,  0.0469,  0.3863,  0.1198,
         -0.0057, -0.2359],
        [-0.0292, -0.0112, -0.3066,  0.1498, -0.1679,  0.0140,  0.0794,  0.1637,
          0.0150, -0.1708]], grad_fn=<AddmmBackward0>)

将模型的参数存储为一个叫做“mlp.params”的文件

In [12]:
torch.save(net.state_dict(), 'mlp.params')

实例化了原始多层感知机的一个备份。直接读取文件中存储的参数

In [13]:
clone = MLP()
clone.load_state_dict(torch.load('mlp.params'))
clone.eval()

MLP(
  (hidden): Linear(in_features=20, out_features=256, bias=True)
  (output): Linear(in_features=256, out_features=10, bias=True)
)

In [17]:
Y_clone = clone(X)

In [18]:
Y_clone == Y

tensor([[True, True, True, True, True, True, True, True, True, True],
        [True, True, True, True, True, True, True, True, True, True],
        [True, True, True, True, True, True, True, True, True, True],
        [True, True, True, True, True, True, True, True, True, True],
        [True, True, True, True, True, True, True, True, True, True],
        [True, True, True, True, True, True, True, True, True, True]])